name: Build

on:
    push:
        branches: [main, next, master, 2.5, 3.4, 4.3, 5.1, 6.3]
    pull_request:
    release:
        types: [created]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Build and test
        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
                operating-system: [ ubuntu-latest, macOS-latest, windows-latest ]
                composer-flags: [""]
                composer-extras: [""]
                stability: ["stable"]
                include:
                    -   php: "8.0"
                        publish-phar: true
                    -   php: "8.0"
                        composer-flags: --prefer-lowest
                    -   php: "8.0"
                        stability: "dev"
                    -   php: "8.1"
                        operating-system: windows-latest

        env:
            COMPOSER_ROOT_VERSION: dev-master

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    ini-values: "phar.readonly=0"

            -   name: Install composer extras
                if: matrix.composer-extras != ''
                run: composer require ${{ matrix.composer-extras }} --no-update

            -   name: Update the minimum stability
                if: matrix.stability == 'dev'
                run: composer config minimum-stability ${{ matrix.stability }}

            -   name: Locate composer cache
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                env:
                    cache-name: cache-composer
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: ${{ hashFiles('composer.json') }}

            -   name: Install composer dependencies
                run: composer update ${{ matrix.composer-flags }}

            -   name: Run static analysis (psalm)
                if: matrix.composer-flags != '--prefer-lowest'
                run: ./vendor/bin/psalm --php-version=${{ matrix.php }}

            -   name: Run tests (phpspec)
                run: bin/phpspec run --format=dot

            -   name: Run tests (phpunit)
                run: ./vendor/bin/phpunit -v

            -   name: Run tests (behat)
                run: ./vendor/bin/behat --format=progress
